title: ""
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What problem or use case are you trying to solve? 
                   Please provide a clear description of the feature request.
      required: true
  - type: textarea
    id: design
    attributes:
      label: UX Design
      description: Describe the UX of the solution you'd like.
      required: false
  - type: textarea
    id: technical
    attributes:
      label: Technical Implementation
      description: Do you have thoughts on the technical implementation?
      required: false
      