name: Small Enhancements
description: Suggest a small enhancement for OpenHands. For feature requests, use Discussions.
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear description of the enhancement.
      placeholder: PLEASE NOTE - If this is feature request, use Discussions.
                   Examples of small enhancements
                   * Adding a model to the basic settings dropdown
                   * Asking for additional documentation
                   * Making a specific UI component expandable
    validations:
      required: true
      